global:
  slack_api_url: 'your slack endpoint'

route:
 group_by: ['alertname']
 group_wait: 3s
 group_interval: 5s
 repeat_interval: 10m
 receiver: slack
receivers:
- name: slack
  slack_configs:
  - channel: '#devops'
    send_resolved: true
    icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
    text: "<!channel> \nsummary: {{ .CommonAnnotations.message }}\n"
