apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_USER
            valueFrom: 
              secretKeyRef:
                  name: mysql-secret
                  key: db_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-secret
                  key: db_user_password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-secret
                  key: db_root_password    
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: configmap
            mountPath: /docker-entrypoint-initdb.d
            
      volumes:
        - name: configmap
          configMap:
             name: mysqlconf
             items:
               - key: mysqlconf.sql
                 path: mysqlconf.sql
        
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP 
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myadmin-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myadmin
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
      - name: myadmin
        image: phpmyadmin/phpmyadmin
        env:
          - name: PMA_PORT
            value: "3306"
          - name: PMA_HOST
            value: mysql-service
           
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: myadmin-service
  namespace: default
  labels:
    app: myadmin
spec:
  type: ClusterIP
  selector:
    app: myadmin
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
      
