apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  abdelali.conf: |
    server{ 
      listen 3000;
      root /usr/share/nginx/html;
      location / {
         index index.html;
      }
    }
#try_files $uri /index.html= 404;