apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  selector:
    run: my-nginx
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 30400
    #protocol: TCP
  - port: 3000
    targetPort: 3000
    #nodePort: 30600
    #protocol: TCP 
  type: ClusterIP